import Header from '@/components/layout/header'
import { Providers } from '@/components/provider/providers'
import { Toaster } from '@/components/ui/sonner'
import type { Metadata } from 'next'
import { getLocale } from 'next-intl/server'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className="antialiased">
        <Providers>
          <Toaster position="top-right" />
          <div className="bg-background flex min-h-svh flex-col">
            <Header />
            <main className="flex flex-1 flex-col">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
